keep_files: ['css', 'js']
include: ['_pages']
relative_permalinks: false
timezone: America/New_York
encoding: utf-8
product: Flannel
keywords: Container Networking, Flannel, Juju, Juju Container Networking
analytics_id: UA-51016932-3
repository: chuckbutler/flannel-docker-charm
forkme_enabled: true
url: http://chuckbutler.github.io/flannel-docker-charm/
