---
- name: Grab the port
  shell: relation-get port
  register: port

- name: Grab the private-address
  shell: relation-get private-address
  register: private_address

- set_fact:
    etcd_port: "{{ port.stdout }}"
    etcd_ip: "{{ private_address.stdout }}"

# Note: removed teh etcd_ip null check because private-address is always
# available on relationships - its passed implicity.
- set_fact:
    etcd_joined: "{{ etcd_port != ''}}"

# initialize_etcd
- name: Initialize ETCD API with Data
  shell: "{{ charm_dir}}/scripts/etcd_rest.py http://{{etcd_ip}}:{{etcd_port}}"
  when: etcd_joined == "True"

- name: Install Upstart Template for flannel
  template: src={{ charm_dir }}/templates/upstart.template
            dest=/etc/init/flannel.conf
            mode=0644
  when: etcd_joined == "True"

- name: Cycle Flannel Service
  service: name=flannel state=restarted enabled=yes
  when: etcd_joined == "True"

# I dont understand why this is here - set on line 157 of hooks.py in flannel charm
# relation-set etcd_endpoint
- name: Send etcd_endpoint data
  shell: "relation-set etcd_endpoint='http://{{ etcd_ip }}:{{ etcd_port }}'"
  when: etcd_joined == "True"

- name: Call network Relation Changed
  include: network-relation-changed.yaml
  when: etcd_joined == "True"
