# Base Install and Upgrade-Charm logic
---

    - name: Install required packages.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
          - bridge-utils

    - name: Unpack the flannel binary
      unarchive: src={{ charm_dir }}/files/flannel.amd64.tar.gz
                 dest=/usr/local/bin
                 creates=/usr/local/bin/flannel mode='u=rx,g=rx,o=rx'
