---

# Note: this is necessary when being called from
# network-relation-changed, not from db-relation-joined.

- name: Find Docker-Host network relation-id
  shell: relation-ids network
  register: docker_host_rel_id

# Read data from flannel config
- name: Read Flannel Subnet
  shell: cat /run/flannel/subnet.env | grep FLANNEL_SUBNET | cut -f2 -d"="
  register: flannel_subnet

- name: Read Flannel MTU
  shell: cat /run/flannel/subnet.env | grep FLANNEL_MTU | cut -f2 -d"="
  register: flannel_mtu

- set_fact:
    host_rel_id: "{{ docker_host_rel_id.stdout }}"
    flannel_mtu: "{{ flannel_mtu.stdout }}"
    flannel_subnet: "{{ flannel_subnet.stdout }}"

- name: Send Data to Docker Host for bridge configuration
  shell: relation-set -r {{ host_rel_id }} flannel-subnet={{ flannel_subnet  }} flannel-mtu={{ flannel_mtu }} overlay-type=udp
  when: host_rel_id != ""
